const PaperType = document.querySelector("#PaperType")
const MetalType = document.querySelector("#MetalType")
const PlasticType = document.querySelector("#PlasticType")
const GlassType = document.querySelector("#GlassType")
const OrgType = document.querySelector("#OrgType")
const inputCadastroName = document.querySelector("#inputCadastroName")
const inputCadastroCelular = document.querySelector("#inputCadastroCelular")
const inputTextArea = document.querySelector("#inputTextArea")
const btn_Enviar = document.querySelector("#inputCadastroEnviar")

